### ISSUE TITLE
Add ec2_metadata_http_tokens in rhcs_cluster_rosa_hcp

### ISSUE THREAD

**Issue by runningman** [terraform-redhat/terraform-rhcs-rosa-hcp#33]
In the 1.6.3 provider a propery for managing ec2 metadata http tokens is available for the rhcs_cluster_rosa_hcp resource but it is not exposed via the module
https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/resources/cluster_rosa_hcp#ec2_metadata_http_tokens

**Comment by gdbranco** [comment]
Should be available since v1.6.4, closing issue. If this is not resolved please reopen with more information
